import React, { useMemo } from "react";
import { glossaryTerms } from "../lib/i18n/glossaryData";
import { useLanguage } from "../lib/i18n/LanguageContext";
import GlossaryTooltip from "./GlossaryTooltip";

// --- EXTENDED BLOCKLIST ---
// These words will NEVER be highlighted/defined.
const GLOBAL_IGNORED_TERMS = [
  // --- Deity & Holy Figures ---
  "God",
  "Lord",
  "Almighty",
  "Creator",
  "Father",
  "Son",
  "Holy Spirit",
  "Spirit",
  "Trinity",
  "Jesus",
  "Christ",
  "Messiah",
  "Savior",
  "Redeemer",
  "Lamb of God",
  "Good Shepherd",
  "Mary",
  "Virgin Mary",
  "Mother of God",
  "Joseph",
  "Saint Joseph",
  "Holy Family",
  "Angel",
  "Archangel",
  "Guardian Angel",
  "Saint",
  "Martyr",
  "Prophet",
  "Apostle",
  "Disciple",
  "Evangelist",
  // French
  "Dieu",
  "Seigneur",
  "Tout-Puissant",
  "Créateur",
  "Père",
  "Fils",
  "Saint-Esprit",
  "Esprit",
  "Trinité",
  "Jésus",
  "Christ",
  "Messie",
  "Sauveur",
  "Rédempteur",
  "Agneau de Dieu",
  "Bon Berger",
  "Marie",
  "Vierge Marie",
  "Mère de Dieu",
  "Joseph",
  "Saint Joseph",
  "Sainte Famille",
  "Ange",
  "Archange",
  "Ange Gardien",
  "Saint",
  "Martyr",
  "Prophète",
  "Apôtre",
  "Disciple",
  "Évangéliste",
  // Spanish
  "Dios",
  "Señor",
  "Todopoderoso",
  "Creador",
  "Padre",
  "Hijo",
  "Espíritu Santo",
  "Espíritu",
  "Trinidad",
  "Jesús",
  "Cristo",
  "Mesías",
  "Salvador",
  "Redentor",
  "Cordero de Dios",
  "Buen Pastor",
  "María",
  "Virgen María",
  "Madre de Dios",
  "José",
  "San José",
  "Sagrada Familia",
  "Ángel",
  "Arcángel",
  "Ángel de la Guarda",
  "Santo",
  "Mártir",
  "Profeta",
  "Apóstol",
  "Discípulo",
  "Evangelista",
  // German
  "Gott",
  "Herr",
  "Allmächtiger",
  "Schöpfer",
  "Vater",
  "Sohn",
  "Heiliger Geist",
  "Geist",
  "Dreifaltigkeit",
  "Jesus",
  "Christus",
  "Messias",
  "Retter",
  "Erlöser",
  "Lamm Gottes",
  "Guter Hirte",
  "Maria",
  "Jungfrau Maria",
  "Mutter Gottes",
  "Josef",
  "Heiliger Josef",
  "Heilige Familie",
  "Engel",
  "Erzengel",
  "Schutzengel",
  "Heiliger",
  "Märtyrer",
  "Prophet",
  "Apostel",
  "Jünger",
  "Evangelist",

  // --- Common Biblical Names ---
  "Adam",
  "Eve",
  "Noah",
  "Abraham",
  "Isaac",
  "Jacob",
  "Moses",
  "Aaron",
  "David",
  "Solomon",
  "Elijah",
  "Peter",
  "Paul",
  "John",
  "James",
  "Andrew",
  "Philip",
  "Thomas",
  "Matthew",
  "Bartholomew",
  "Simon",
  "Jude",
  "Judas",
  "Matthias",
  "Mark",
  "Luke",
  "Timothy",
  "Titus",
  "Barnabas",
  "Stephen",
  // French
  "Adam",
  "Ève",
  "Noé",
  "Abraham",
  "Isaac",
  "Jacob",
  "Moïse",
  "Aaron",
  "David",
  "Salomon",
  "Élie",
  "Pierre",
  "Paul",
  "Jean",
  "Jacques",
  "André",
  "Philippe",
  "Thomas",
  "Matthieu",
  "Barthélemy",
  "Simon",
  "Jude",
  "Judas",
  "Matthias",
  "Marc",
  "Luc",
  "Timothée",
  "Tite",
  "Barnabé",
  "Étienne",
  // Spanish
  "Adán",
  "Eva",
  "Noé",
  "Abrahán",
  "Isaac",
  "Jacob",
  "Moisés",
  "Aarón",
  "David",
  "Salomón",
  "Elías",
  "Pedro",
  "Pablo",
  "Juan",
  "Santiago",
  "Andrés",
  "Felipe",
  "Tomás",
  "Mateo",
  "Bartolomé",
  "Simón",
  "Judas",
  "Matías",
  "Marcos",
  "Lucas",
  "Timoteo",
  "Tito",
  "Bernabé",
  "Esteban",
  // German
  "Adam",
  "Eva",
  "Noah",
  "Abraham",
  "Isaak",
  "Jakob",
  "Mose",
  "Aaron",
  "David",
  "Salomo",
  "Elija",
  "Petrus",
  "Paulus",
  "Johannes",
  "Jakobus",
  "Andreas",
  "Philippus",
  "Thomas",
  "Matthäus",
  "Bartholomäus",
  "Simon",
  "Judas",
  "Matthias",
  "Markus",
  "Lukas",
  "Timotheus",
  "Titus",
  "Barnabas",
  "Stephanus",

  // --- Scripture & Texts ---
  "Bible",
  "Scripture",
  "Holy Scripture",
  "Word of God",
  "Old Testament",
  "New Testament",
  "Gospel",
  "Epistle",
  "Letter",
  "Psalm",
  "Proverb",
  "Revelation",
  "Chapter",
  "Verse",
  "Text",
  // French
  "Bible",
  "Écriture",
  "Sainte Écriture",
  "Parole de Dieu",
  "Ancien Testament",
  "Nouveau Testament",
  "Évangile",
  "Épître",
  "Lettre",
  "Psaume",
  "Proverbe",
  "Apocalypse",
  "Chapitre",
  "Verset",
  "Texte",
  // Spanish
  "Biblia",
  "Escritura",
  "Sagrada Escritura",
  "Palabra de Dios",
  "Antiguo Testamento",
  "Nuevo Testamento",
  "Evangelio",
  "Epístola",
  "Carta",
  "Salmo",
  "Proverbio",
  "Revelación",
  "Capítulo",
  "Versículo",
  "Texto",
  // German
  "Bibel",
  "Schrift",
  "Heilige Schrift",
  "Wort Gottes",
  "Altes Testament",
  "Neues Testament",
  "Evangelium",
  "Epistel",
  "Brief",
  "Psalm",
  "Sprüche",
  "Offenbarung",
  "Kapitel",
  "Vers",
  "Text",

  // --- Church Structure & Roles ---
  "Church",
  "Catholic",
  "Roman Catholic",
  "Christian",
  "Christianity",
  "Protestant",
  "Protestantism",
  "Orthodox",
  "Pope",
  "Papacy",
  "Cardinal",
  "Bishop",
  "Archbishop",
  "Priest",
  "Deacon",
  "Clergy",
  "Laity",
  "Layperson",
  "Monk",
  "Nun",
  "Sister",
  "Brother",
  "Friar",
  "Abbot",
  "Abbess",
  "Superior",
  "Diocese",
  "Parish",
  "Vatican",
  "Holy See",
  "Rome",
  "Magisterium",
  "Hierarchy",
  // French
  "Église",
  "Catholique",
  "Catholique Romain",
  "Chrétien",
  "Christianisme",
  "Protestant",
  "Protestantisme",
  "Orthodoxe",
  "Pape",
  "Papauté",
  "Cardinal",
  "Évêque",
  "Archevêque",
  "Prêtre",
  "Diacre",
  "Clergé",
  "Laïcs",
  "Laïc",
  "Moine",
  "Nonne",
  "Sœur",
  "Frère",
  "Abbé",
  "Abbesse",
  "Supérieur",
  "Diocèse",
  "Paroisse",
  "Vatican",
  "Saint-Siège",
  "Rome",
  "Magistère",
  "Hiérarchie",
  // Spanish
  "Iglesia",
  "Católico",
  "Católico Romano",
  "Cristiano",
  "Cristianismo",
  "Protestante",
  "Protestantismo",
  "Ortodoxo",
  "Papa",
  "Papado",
  "Cardenal",
  "Obispo",
  "Arzobispo",
  "Sacerdote",
  "Diácono",
  "Clero",
  "Laicos",
  "Laico",
  "Monje",
  "Monja",
  "Hermana",
  "Hermano",
  "Fraile",
  "Abad",
  "Abadesa",
  "Superior",
  "Diócesis",
  "Parroquia",
  "Vaticano",
  "Santa Sede",
  "Roma",
  "Magisterio",
  "Jerarquía",
  // German
  "Kirche",
  "Katholisch",
  "Römisch-Katholisch",
  "Christ",
  "Christentum",
  "Protestant",
  "Protestantismus",
  "Orthodox",
  "Papst",
  "Papsttum",
  "Kardinal",
  "Bischof",
  "Erzbischof",
  "Priester",
  "Diakon",
  "Klerus",
  "Laien",
  "Laie",
  "Mönch",
  "Nonne",
  "Schwester",
  "Bruder",
  "Abte",
  "Äbtissin",
  "Vorgesetzter",
  "Diözese",
  "Pfarrei",
  "Vatikan",
  "Heiliger Stuhl",
  "Rom",
  "Lehramt",
  "Hierarchie",

  // --- Liturgy & Sacraments (Common Terms) ---
  "Mass",
  "Liturgy",
  "Service",
  "Rite",
  "Ritual",
  "Ceremony",
  "Celebration",
  "Sacrament",
  "Baptism",
  "Confirmation",
  "Eucharist",
  "Communion",
  "Holy Communion",
  "Confession",
  "Penance",
  "Reconciliation",
  "Matrimony",
  "Marriage",
  "Holy Orders",
  "Ordination",
  "Anointing",
  "Blessing",
  "Benediction",
  "Consecration",
  "Dedication",
  "Prayer",
  "Pray",
  "Worship",
  "Adoration",
  "Praise",
  "Thanksgiving",
  "Petition",
  "Intercession",
  "Homily",
  "Sermon",
  "Preaching",
  "Reading",
  "Gospel Reading",
  "Sign of the Cross",
  "Amen",
  "Alleluia",
  // French
  "Messe",
  "Liturgie",
  "Service",
  "Rite",
  "Rituel",
  "Cérémonie",
  "Célébration",
  "Sacrement",
  "Baptême",
  "Confirmation",
  "Eucharistie",
  "Communion",
  "Sainte Communion",
  "Confession",
  "Pénitence",
  "Réconciliation",
  "Matrimoine",
  "Mariage",
  "Ordre",
  "Ordination",
  "Onction",
  "Bénédiction",
  "Consécration",
  "Dédicace",
  "Prière",
  "Prier",
  "Culte",
  "Adoration",
  "Louange",
  "Action de Grâce",
  "Pétition",
  "Intercession",
  "Homélie",
  "Sermon",
  "Prédication",
  "Lecture",
  "Lecture d'Évangile",
  "Signe de la Croix",
  "Amen",
  "Alléluia",
  // Spanish
  "Misa",
  "Liturgia",
  "Servicio",
  "Rito",
  "Ritual",
  "Ceremonia",
  "Celebración",
  "Sacramento",
  "Bautismo",
  "Confirmación",
  "Eucaristía",
  "Comunión",
  "Sagrada Comunión",
  "Confesión",
  "Penitencia",
  "Reconciliación",
  "Matrimonio",
  "Orden Sacerdotal",
  "Ordenación",
  "Unción",
  "Bendición",
  "Consagración",
  "Dedicación",
  "Oración",
  "Orar",
  "Culto",
  "Adoración",
  "Alabanza",
  "Acción de Gracias",
  "Petición",
  "Intercesión",
  "Homilía",
  "Sermón",
  "Predicación",
  "Lectura",
  "Lectura del Evangelio",
  "Señal de la Cruz",
  "Amén",
  "Aleluya",
  // German
  "Messe",
  "Liturgie",
  "Gottesdienst",
  "Ritus",
  "Ritual",
  "Zeremonie",
  "Feier",
  "Sakrament",
  "Taufe",
  "Firmung",
  "Eucharistie",
  "Kommunion",
  "Heilige Kommunion",
  "Beichte",
  "Buße",
  "Versöhnung",
  "Ehe",
  "Priesterweihe",
  "Weihe",
  "Salbung",
  "Segen",
  "Konsekration",
  "Weihung",
  "Gebet",
  "Beten",
  "Anbetung",
  "Lob",
  "Dank",
  "Bitte",
  "Fürbitte",
  "Predigt",
  "Lesung",
  "Kreuzzeichen",
  "Amen",
  "Halleluja",

  // --- Theological Concepts (Common) ---
  "Faith",
  "Hope",
  "Charity",
  "Love",
  "Grace",
  "Mercy",
  "Justice",
  "Peace",
  "Joy",
  "Salvation",
  "Redemption",
  "Justification",
  "Sanctification",
  "Holiness",
  "Glory",
  "Sin",
  "Evil",
  "Devil",
  "Satan",
  "Demon",
  "Hell",
  "Purgatory",
  "Heaven",
  "Paradise",
  "Kingdom of God",
  "Life",
  "Death",
  "Eternal Life",
  "Resurrection",
  "Ascension",
  "Incarnation",
  "Virgin Birth",
  "Soul",
  "Body",
  "Spirit",
  "Flesh",
  "Heart",
  "Mind",
  "Conscience",
  "Free Will",
  "Reason",
  "Will",
  "Truth",
  "Wisdom",
  "Knowledge",
  "Understanding",
  "Miracle",
  "Sign",
  "Symbol",
  "Covenant",
  "Commandment",
  "Law",
  "Doctrine",
  "Dogma",
  "Teaching",
  "Tradition",
  "Virtue",
  "Vice",
  "Good",
  "Bad",
  "Right",
  "Wrong",
  "Moral",
  "Morality",
  "Ethics",
  // French
  "Foi",
  "Espérance",
  "Charité",
  "Amour",
  "Grâce",
  "Miséricorde",
  "Justice",
  "Paix",
  "Joie",
  "Salut",
  "Rédemption",
  "Justification",
  "Sanctification",
  "Sainteté",
  "Gloire",
  "Péché",
  "Mal",
  "Diable",
  "Satan",
  "Démon",
  "Enfer",
  "Purgatoire",
  "Ciel",
  "Paradis",
  "Royaume de Dieu",
  "Vie",
  "Mort",
  "Vie Éternelle",
  "Résurrection",
  "Ascension",
  "Incarnation",
  "Naissance Virginale",
  "Âme",
  "Corps",
  "Esprit",
  "Chair",
  "Cœur",
  "Esprit",
  "Conscience",
  "Libre Arbitre",
  "Raison",
  "Volonté",
  "Vérité",
  "Sagesse",
  "Connaissance",
  "Compréhension",
  "Miracle",
  "Signe",
  "Symbole",
  "Alliance",
  "Commandement",
  "Loi",
  "Doctrine",
  "Dogme",
  "Enseignement",
  "Tradition",
  "Vertu",
  "Vice",
  "Bien",
  "Mauvais",
  "Droit",
  "Faux",
  "Moral",
  "Moralité",
  "Éthique",
  // Spanish
  "Fe",
  "Esperanza",
  "Caridad",
  "Amor",
  "Gracia",
  "Misericordia",
  "Justicia",
  "Paz",
  "Gozo",
  "Salvación",
  "Redención",
  "Justificación",
  "Santificación",
  "Santidad",
  "Gloria",
  "Pecado",
  "Mal",
  "Diablo",
  "Satanás",
  "Demonio",
  "Infierno",
  "Purgatorio",
  "Cielo",
  "Paraíso",
  "Reino de Dios",
  "Vida",
  "Muerte",
  "Vida Eterna",
  "Resurrección",
  "Ascensión",
  "Encarnación",
  "Nacimiento Virginal",
  "Alma",
  "Cuerpo",
  "Espíritu",
  "Carne",
  "Corazón",
  "Mente",
  "Conciencia",
  "Libre Albedrío",
  "Razón",
  "Voluntad",
  "Verdad",
  "Sabiduría",
  "Conocimiento",
  "Comprensión",
  "Milagro",
  "Signo",
  "Símbolo",
  "Alianza",
  "Mandamiento",
  "Ley",
  "Doctrina",
  "Dogma",
  "Enseñanza",
  "Tradición",
  "Virtud",
  "Vicio",
  "Bien",
  "Malo",
  "Correcto",
  "Falso",
  "Moral",
  "Moralidad",
  "Ética",
  // German
  "Glaube",
  "Hoffnung",
  "Nächstenliebe",
  "Liebe",
  "Gnade",
  "Barmherzigkeit",
  "Gerechtigkeit",
  "Friede",
  "Freude",
  "Erlösung",
  "Rechtfertigung",
  "Heiligung",
  "Heiligkeit",
  "Herrlichkeit",
  "Sünde",
  "Böses",
  "Teufel",
  "Satan",
  "Dämon",
  "Hölle",
  "Fegefeuer",
  "Himmel",
  "Paradies",
  "Reich Gottes",
  "Leben",
  "Tod",
  "Ewiges Leben",
  "Auferstehung",
  "Himmelfahrt",
  "Menschwerdung",
  "Jungfrauengeburt",
  "Seele",
  "Leib",
  "Geist",
  "Fleisch",
  "Herz",
  "Verstand",
  "Gewissen",
  "Freier Wille",
  "Vernunft",
  "Wille",
  "Wahrheit",
  "Weisheit",
  "Wissen",
  "Verständnis",
  "Wunder",
  "Zeichen",
  "Symbol",
  "Bund",
  "Gebot",
  "Gesetz",
  "Lehre",
  "Dogma",
  "Tradition",
  "Tugend",
  "Laster",
  "Gut",
  "Schlecht",
  "Richtig",
  "Falsch",
  "Moral",
  "Ethik",

  // --- Objects & Places ---
  "Cross",
  "Crucifix",
  "Rosary",
  "Altar",
  "Tabernacle",
  "Sanctuary",
  "Nave",
  "Choir",
  "Cathedral",
  "Basilica",
  "Chapel",
  "Shrine",
  "Temple",
  "Synagogue",
  "Bread",
  "Wine",
  "Body and Blood",
  "Host",
  "Chalice",
  "Candle",
  "Incense",
  "Holy Water",
  "Vestment",
  "Robes",
  "Image",
  "Statue",
  "Icon",
  "Painting",
  "Book",
  // French
  "Croix",
  "Crucifix",
  "Rosaire",
  "Autel",
  "Tabernacle",
  "Sanctuaire",
  "Nef",
  "Chœur",
  "Cathédrale",
  "Basilique",
  "Chapelle",
  "Sanctuaire",
  "Temple",
  "Synagogue",
  "Pain",
  "Vin",
  "Corps et Sang",
  "Hostie",
  "Calice",
  "Bougie",
  "Encens",
  "Eau Bénite",
  "Vêtement",
  "Robes",
  "Image",
  "Statue",
  "Icône",
  "Peinture",
  "Livre",
  // Spanish
  "Cruz",
  "Crucifijo",
  "Rosario",
  "Altar",
  "Sagrario",
  "Santuario",
  "Nave",
  "Coro",
  "Catedral",
  "Basílica",
  "Capilla",
  "Santuario",
  "Templo",
  "Sinagoga",
  "Pan",
  "Vino",
  "Cuerpo y Sangre",
  "Hostia",
  "Cáliz",
  "Vela",
  "Incienso",
  "Agua Bendita",
  "Vestimenta",
  "Túnica",
  "Imagen",
  "Estatua",
  "Icono",
  "Pintura",
  "Libro",
  // German
  "Kreuz",
  "Kruzifix",
  "Rosenkranz",
  "Altar",
  "Tabernakel",
  "Altarraum",
  "Kirchenschiff",
  "Chor",
  "Kathedrale",
  "Basilika",
  "Kapelle",
  "Schrein",
  "Tempel",
  "Synagoge",
  "Brot",
  "Wein",
  "Leib und Blut",
  "Hostie",
  "Kelch",
  "Kerze",
  "Weihrauch",
  "Weihwasser",
  "Gewand",
  "Ikone",
  "Buch",

  // --- Seasons & Days ---
  "Advent",
  "Christmas",
  "Lent",
  "Easter",
  "Pentecost",
  "Sunday",
  "Sabbath",
  "Holy Week",
  "Good Friday",
  // French
  "Avent",
  "Noël",
  "Carême",
  "Pâques",
  "Pentecôte",
  "Dimanche",
  "Sabbat",
  "Semaine Sainte",
  "Vendredi Saint",
  // Spanish
  "Adviento",
  "Navidad",
  "Cuaresma",
  "Pascua",
  "Pentecostés",
  "Domingo",
  "Sábado",
  "Semana Santa",
  "Viernes Santo",
  // German
  "Advent",
  "Weihnachten",
  "Fastenzeit",
  "Ostern",
  "Pfingsten",
  "Sonntag",
  "Sabbat",
  "Karwoche",
  "Karfreitag",

  // --- General/Abstract ---
  "Religion",
  "Religious",
  "Spiritual",
  "Spirituality",
  "Divine",
  "Human",
  "Natural",
  "Supernatural",
  "World",
  "Creation",
  "Universe",
  "Earth",
  "Man",
  "Woman",
  "Child",
  "Family",
  "Community",
  "Society",
  "History",
  "Historical",
  "Tradition",
  "Traditional",
  "Modern",
  "Ancient",
  "Time",
  "Eternity",
  "Beginning",
  "End",
  "Alpha",
  "Omega",
  "Light",
  "Darkness",
  // French
  "Religion",
  "Religieux",
  "Spirituel",
  "Spiritualité",
  "Divin",
  "Humain",
  "Naturel",
  "Surnaturel",
  "Monde",
  "Création",
  "Univers",
  "Terre",
  "Homme",
  "Femme",
  "Enfant",
  "Famille",
  "Communauté",
  "Société",
  "Histoire",
  "Historique",
  "Tradition",
  "Traditionnel",
  "Moderne",
  "Ancien",
  "Temps",
  "Éternité",
  "Début",
  "Fin",
  "Lumière",
  "Ténèbres",
  // Spanish
  "Religión",
  "Religioso",
  "Espiritual",
  "Espiritualidad",
  "Divino",
  "Humano",
  "Natural",
  "Sobrenatural",
  "Mundo",
  "Creación",
  "Universo",
  "Tierra",
  "Hombre",
  "Mujer",
  "Niño",
  "Familia",
  "Comunidad",
  "Sociedad",
  "Historia",
  "Histórico",
  "Tradición",
  "Tradicional",
  "Moderno",
  "Antiguo",
  "Tiempo",
  "Eternidad",
  "Comienzo",
  "Fin",
  "Luz",
  "Oscuridad",
  // German
  "Religion",
  "Religiös",
  "Geistlich",
  "Spiritualität",
  "Göttlich",
  "Menschlich",
  "Natürlich",
  "Übernatürlich",
  "Welt",
  "Schöpfung",
  "Universum",
  "Erde",
  "Mann",
  "Frau",
  "Kind",
  "Familie",
  "Gemeinschaft",
  "Gesellschaft",
  "Geschichte",
  "Historisch",
  "Tradition",
  "Traditionell",
  "Modern",
  "Antik",
  "Zeit",
  "Ewigkeit",
  "Anfang",
  "Ende",
  "Licht",
  "Dunkelheit",
];

interface SmartTextProps {
  children: React.ReactNode;
  ignore?: string[]; // Optional: Pass specific words to ignore on a specific page
}

export default function SmartText({
  children,
  ignore = [],
}: SmartTextProps) {
  const { language } = useLanguage();

  // 1. Prepare the map of terms for the current language
  const termsMap = useMemo(() => {
    const map = new Map();

    // Combine global blocklist with any local page-specific ignores
    // We convert to lowercase for case-insensitive comparison
    const blocklist = new Set(
      [...GLOBAL_IGNORED_TERMS, ...ignore].map((w) =>
        w.toLowerCase(),
      ),
    );

    // SAFETY FIX: Filter out any undefined/empty items from the data first
    const validTerms = glossaryTerms.filter(
      (item) => item && item.term,
    );

    // We sort terms by length (Longest -> Shortest).
    // Why? So we match "Hypostatic Union" before we match just "Union" (if "Union" was a term).
    validTerms.sort((a, b) => {
      const getLen = (item: any) => {
        const t = item.term[language] || item.term["en"] || "";
        return t.length;
      };
      return getLen(b) - getLen(a);
    });

    validTerms.forEach((term) => {
      // Get the term in the current language (or fallback to English)
      // Using 'any' casting for safety with dynamic keys
      const termObj = term.term as any;
      const text = termObj[language] || termObj["en"];

      if (text) {
        const lowerText = text.toLowerCase();
        // Only add if it's NOT in our blocklist
        if (!blocklist.has(lowerText)) {
          map.set(lowerText, term);
        }
      }
    });
    return map;
  }, [language, ignore]);

  // 2. Recursive function to process text nodes within React children
  const processText = (text: string): React.ReactNode[] => {
    if (!text) return [text];

    // Create a regex pattern from all glossary keys
    // We escape special regex characters to prevent errors
    const keys = Array.from(termsMap.keys());
    if (keys.length === 0) return [text];

    const termsPattern = keys
      .map((t) => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
      .join("|");

    // Match whole words only (\b)
    const regex = new RegExp(`\\b(${termsPattern})\\b`, "gi");

    const parts = text.split(regex);

    return parts.map((part, index) => {
      const lowerPart = part.toLowerCase();
      const termData = termsMap.get(lowerPart);

      if (termData) {
        return (
          <GlossaryTooltip
            key={`${part}-${index}`}
            word={part}
            termData={termData}
          />
        );
      }
      return part;
    });
  };

  // 3. Helper to traverse the React Component tree
  // This ensures we only replace text inside strings, not breaking other HTML/Components
  const traverse = (node: React.ReactNode): React.ReactNode => {
    if (typeof node === "string") {
      return processText(node);
    }

    if (Array.isArray(node)) {
      return node.map((child, i) => (
        <span key={i}>{traverse(child)}</span>
      ));
    }

    if (
      typeof node === "object" &&
      node !== null &&
      "props" in node
    ) {
      const element = node as React.ReactElement;
      // If the element has children, process them recursively
      if (element.props && element.props.children) {
        return React.cloneElement(element, {
          ...element.props,
          children: traverse(element.props.children),
        });
      }
    }

    return node;
  };

  // 4. Run the processor
  return <>{traverse(children)}</>;
}